// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.8.2_eslint@8.55.0_typescript@5.3.2_vite@4.5.1_vue-tsc@1.8.24/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/__i18n__/precompile': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.12_vue-router@4.2.5_vue@3.3.10/node_modules/@nuxtjs/i18n/dist/runtime/server/precompile').default>>>>
    }
    '/__i18n__/prerender/:hash': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.12_vue-router@4.2.5_vue@3.3.10/node_modules/@nuxtjs/i18n/dist/runtime/server/dynamic').default>>>>
    }
  }
}
export {}